services:
  nginx:
    image: nginx
    networks:
      inception:
    build: ./requirements/nginx/
    ports:
      - 443:443
    depends_on:
      - wordpress

  wordpress:
    image: wordpress
    networks:
      inception:
    links:
      - mariadb
    build: ./requirements/nginx/
    volumes:
      - wordpress_app:/var/www/html
    env_file:
      - .env

  mariadb:
    image: mariadb
    networks:
      inception:
    # build: ./requirements/mariadb/
    ports:
      - 3306:3306
    volumes:
      - maria_db:/var/lib/mysql
    env_file:
      - .env

volumes:
  wordpress_app:
  maria_db:

networks:
  inception:
    driver: bridge