services:
  my_nginx:
    container_name: c_nginx
    image: nginx
    ports:
      - 8080:80
      - 8081:80
  my_html:
    container_name: c_html
    image: httpd
    volumes:
      - C:/Users/mucoox/Desktop/42inception/ilkdeneme/html:/usr/local/apache2/htdocs/
    ports:
      - 9090:80
      - 9091:80

volumes:
  html: 